### PR TITLE
fix warnings on 0.4

### PR DESCRIPTION
**Pull request by rened**

### CODE REVIEW

**Comment by johnmyleswhite** [comment]
Conflicts?

**Comment by rened** [comment]
Yes, I really don't get those. Base off of master, but the network graph shows otherwise. Can't rebase on top of master because it already is, according to git...

**Comment by johnmyleswhite** [comment]
Maybe you need a clean clone?

**Comment by rened** [comment]
doh... fixed on master. Sorry for the noise...

**Pull request closed without merging**
